### ISSUE TITLE
Update samples to Akka 2.6 and Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka-samples#132]
Update all samples Akka 2.6 and convert to Akka Typed (if relevant). Also revisit if the sample makes sense, adds value or should be removed.

Creating this as an overview, even though not all samples are located in this repository.

- [x] https://github.com/akka/akka-samples/pull/170 akka-sample-cluster-client-grpc-java
  * update to final version
- [x] https://github.com/akka/akka-samples/pull/170 akka-sample-cluster-client-grpc-scala
  * update to final version
- [x] #142 akka-sample-cluster-java
  * update version
- [x] #137 akka-sample-cluster-scala
  * update version
- [x] https://github.com/akka/akka-samples/pull/135 akka-sample-cqrs-scala
  * update version
- [x] https://github.com/akka/akka-samples/pull/141 akka-sample-cqrs-java
  * new
- [x] https://github.com/akka/akka-samples/pull/153 akka-sample-distributed-data-java
  * update version
- [x] https://github.com/akka/akka-samples/pull/134 akka-sample-distributed-data-scala
  * update version
- [x] (@chbatey) https://github.com/akka/akka-samples/pull/138 akka-sample-fsm-java
  * update version
- [x] (@chbatey) https://github.com/akka/akka-samples/pull/138 akka-sample-fsm-scala
  * update version
- [x] https://github.com/akka/akka-samples/pull/133 akka-sample-main-java
  * remove
- [x] https://github.com/akka/akka-samples/pull/133 akka-sample-main-scala
  * remove
- [x] akka-sample-multi-node-scala
  * drop, refer to cluster sample instead
- [x] https://github.com/akka/akka-samples/pull/174 akka-sample-osgi-dining-hakkers
  * remove for now
- [x] https://github.com/akka/akka-samples/pull/140 akka-sample-persistence-dc-java
  * update version
- [x] https://github.com/akka/akka-samples/pull/140 akka-sample-persistence-dc-scala
  * update version
- [x] https://github.com/akka/akka-samples/pull/149 akka-sample-persistence-java
  * update version
- [x] https://github.com/akka/akka-samples/pull/143 akka-sample-persistence-scala
  * update version
- [x] (@patriknw) akka-sample-persistence-typed-scala
  * fold into akka-sample-persistence-scala (only keep Typed)
- [x] (@helena) akka-sample-sharding-java
  * update version
- [x] https://github.com/akka/akka-samples/pull/136 akka-sample-sharding-scala
  * update version
- [x] #147 akka-sample-supervision-java
  * drop
- [x] https://github.com/akka/akka-samples/pull/169 akka-sample-vavr
  * remove
- [x] akka-quickstart-scala.g8
  * already converted to Typed
  * update to final version
- [x] akka-quickstart-java.g8
  * already converted to Typed
  * update to final version
- [x] https://github.com/akka/akka-http-quickstart-scala.g8/pull/70 akka-http-quickstart-scala.g8
  * update version
- [x] https://github.com/akka/akka-http-quickstart-java.g8/pull/45 akka-http-quickstart-java.g8
  * update version
- [x] ~~(@chbatey) akka-grpc-quickstart-scala.g8~~ uses latest stable and has no actors
  ~~* update version~~
- [x] ~~(@chbatey) akka-grpc-quickstart-java.g8~~ uses latest stable and has no actors
  ~~* update version~~
- [x] (@chbatey) akka-distributed-workers-scala.g8 - please review here before finishing in repo: https://github.com/chbatey/akka-distribured-workers-typed/pull/1
  * update version
- ~~[ ] (@chbatey) distributed-workers-java~~ was never ported to Java
  ~~* update version~~
- [x] (@johanandren) akka-sample-cluster-docker-compose-scala
  * update version
- [x] (@chbatey) https://github.com/akka/akka-sample-cluster-kubernetes-java/pull/12 akka-sample-cluster-kubernetes-java
  * update version
- [x] (@chbatey) https://github.com/akka/akka-grpc-sample-kubernetes-scala/pull/56 akka-grpc-sample-kubernetes-scala
  * update version
- [x] akka/akka-sample-cluster-docker-compose-java#45 akka-sample-cluster-docker-compose-java
  * update version
- [x] (@chbatey) https://github.com/akka/akka-sample-cluster-kubernetes-dns-java/pull/25 akka-sample-cluster-kubernetes-dns-java
  * update version
- [x] (@chbatey) https://github.com/akka/akka-upgrade-testing/pull/2 akka-upgrade-testing
  * update version
- [ ] akka-kubernetes-tests
  * update version
- [x] (@johanandren) alpakka-samples
  * update version

**Comment by patriknw** [comment]
I think that concludes this massive ticket. Great work everyone.
